"""
Worker / Validator / Thinker role architecture for LLM-TeamGym.

Implements topology-aware coordination of LLM agent teams following the
three-role paradigm from the PhD thesis on multi-agent coordination:

  Workers   -- propose candidate actions given the game state.
  Validators -- evaluate and approve/reject worker proposals.
  Thinkers  -- integrate validated proposals into a single team action.

The TeamOrchestrator runs one deliberation round:

    Workers propose  -->  Validators validate  -->  Thinker integrates
                                                          |
                                                     final action

Topology constraints are respected: only Worker-Validator pairs that share
an edge in the topology graph interact during the validation phase.

All classes rely exclusively on the standard library (no external deps).
"""

from __future__ import annotations

import enum
import logging
from dataclasses import dataclass, field
from typing import Any, Dict, FrozenSet, List, Optional, Set, Tuple

from llm_team_gym.core.base_agent import BaseAgent
from llm_team_gym.core.base_game import Action, AgentID, Observation

logger = logging.getLogger(__name__)


# ======================================================================
# Role Enum
# ======================================================================

class Role(enum.Enum):
    """The three canonical roles in the Worker/Validator/Thinker paradigm."""

    WORKER = "worker"
    VALIDATOR = "validator"
    THINKER = "thinker"

    def __repr__(self) -> str:
        return f"Role.{self.name}"


# ======================================================================
# Data classes for inter-role messages
# ======================================================================

@dataclass(frozen=True)
class Proposal:
    """A candidate action proposed by a WorkerAgent.

    Attributes
    ----------
    agent_id : AgentID
        The worker that produced this proposal.
    action : Action
        The proposed game action.
    confidence : float
        Self-assessed confidence in [0, 1].
    rationale : str
        Free-text explanation of why this action was chosen.
    """

    agent_id: AgentID
    action: Action
    confidence: float
    rationale: str

    def __post_init__(self) -> None:
        if not (0.0 <= self.confidence <= 1.0):
            raise ValueError(
                f"Proposal confidence must be in [0, 1], got {self.confidence}"
            )


@dataclass(frozen=True)
class Verdict:
    """A validation judgement issued by a ValidatorAgent.

    Attributes
    ----------
    proposal : Proposal
        The proposal being evaluated.
    approved : bool
        Whether the validator endorses this proposal.
    reason : str
        Free-text justification for the decision.
    validator_id : AgentID
        The validator that issued this verdict.
    """

    proposal: Proposal
    approved: bool
    reason: str
    validator_id: AgentID


@dataclass
class RoundResult:
    """Complete record of a single deliberation round.

    Attributes
    ----------
    proposals : list[Proposal]
        All proposals generated by workers.
    verdicts : list[Verdict]
        All verdicts generated by validators.
    final_action : Action
        The action selected by the thinker after integration.
    llm_calls : int
        Total number of ``choose_action`` invocations during the round
        (useful for cost tracking and budgeting).
    """

    proposals: List[Proposal]
    verdicts: List[Verdict]
    final_action: Action
    llm_calls: int


# ======================================================================
# RoleAssignment
# ======================================================================

class RoleAssignment:
    """Maps agent IDs to roles and validates team-composition constraints.

    Two regimes are supported:

    **Standard teams** (>= 3 agents):
        At least one Worker, one Validator, and one Thinker are required.

    **Small teams** (2 agents):
        At least one Worker and one Validator are required.  If no explicit
        Thinker is present the first Validator implicitly doubles as the
        Thinker (the ``implicit_thinker`` property exposes this).

    Parameters
    ----------
    mapping : dict[AgentID, Role]
        Agent-to-role assignment.

    Raises
    ------
    ValueError
        If the mapping violates a composition constraint.
    """

    def __init__(self, mapping: Dict[AgentID, Role]) -> None:
        if not mapping:
            raise ValueError("RoleAssignment requires at least one agent.")
        self._mapping: Dict[AgentID, Role] = dict(mapping)
        self._validate()

    # ---- construction helpers ----------------------------------------

    @classmethod
    def from_lists(
        cls,
        workers: List[AgentID],
        validators: List[AgentID],
        thinkers: Optional[List[AgentID]] = None,
    ) -> "RoleAssignment":
        """Build a RoleAssignment from per-role agent-id lists."""
        mapping: Dict[AgentID, Role] = {}
        for aid in workers:
            mapping[aid] = Role.WORKER
        for aid in validators:
            mapping[aid] = Role.VALIDATOR
        for aid in (thinkers or []):
            mapping[aid] = Role.THINKER
        return cls(mapping)

    # ---- validation --------------------------------------------------

    def _validate(self) -> None:
        workers = self.workers
        validators = self.validators
        thinkers = self.thinkers
        n = len(self._mapping)

        if not workers:
            raise ValueError(
                "RoleAssignment must include at least one WORKER."
            )
        if not validators:
            raise ValueError(
                "RoleAssignment must include at least one VALIDATOR."
            )

        # Standard regime: >= 3 agents require an explicit Thinker.
        if n >= 3 and not thinkers:
            raise ValueError(
                "Teams with 3+ agents must include at least one THINKER. "
                "Assign a THINKER role or reduce the team to 2 agents for "
                "implicit-thinker mode."
            )

    # ---- queries -----------------------------------------------------

    @property
    def workers(self) -> List[AgentID]:
        """Agent IDs assigned to WORKER."""
        return [aid for aid, r in self._mapping.items() if r is Role.WORKER]

    @property
    def validators(self) -> List[AgentID]:
        """Agent IDs assigned to VALIDATOR."""
        return [aid for aid, r in self._mapping.items() if r is Role.VALIDATOR]

    @property
    def thinkers(self) -> List[AgentID]:
        """Agent IDs assigned to THINKER."""
        return [aid for aid, r in self._mapping.items() if r is Role.THINKER]

    @property
    def implicit_thinker(self) -> Optional[AgentID]:
        """Return the implicit thinker for small teams, or ``None``.

        In a 2-agent team with no explicit THINKER the first VALIDATOR
        assumes the thinker responsibility.
        """
        if self.thinkers:
            return None
        return self.validators[0]

    @property
    def effective_thinkers(self) -> List[AgentID]:
        """Thinkers that will actually perform integration (explicit or implicit)."""
        if self.thinkers:
            return list(self.thinkers)
        implicit = self.implicit_thinker
        return [implicit] if implicit is not None else []

    def role_of(self, agent_id: AgentID) -> Role:
        """Return the role assigned to *agent_id*."""
        try:
            return self._mapping[agent_id]
        except KeyError:
            raise KeyError(
                f"Agent '{agent_id}' is not present in this RoleAssignment."
            )

    @property
    def agent_ids(self) -> List[AgentID]:
        """All agent IDs in assignment order."""
        return list(self._mapping.keys())

    def __len__(self) -> int:
        return len(self._mapping)

    def __contains__(self, agent_id: AgentID) -> bool:
        return agent_id in self._mapping

    def __repr__(self) -> str:
        parts = ", ".join(f"{aid}={r.name}" for aid, r in self._mapping.items())
        return f"RoleAssignment({parts})"


# ======================================================================
# Topology
# ======================================================================

class Topology:
    """Undirected graph describing which agents may communicate.

    Edges are stored as frozensets of agent-id pairs.  The primary use-case
    is restricting which Workers a Validator may evaluate (and vice versa).

    If no topology is specified the TeamOrchestrator defaults to
    ``Topology.fully_connected(agent_ids)``.
    """

    def __init__(self, edges: Optional[List[Tuple[AgentID, AgentID]]] = None) -> None:
        self._edges: Set[FrozenSet[AgentID]] = set()
        self._adjacency: Dict[AgentID, Set[AgentID]] = {}
        for u, v in (edges or []):
            self.add_edge(u, v)

    # ---- mutation ----------------------------------------------------

    def add_edge(self, u: AgentID, v: AgentID) -> None:
        """Add an undirected edge between *u* and *v*."""
        edge = frozenset((u, v))
        if edge in self._edges:
            return
        self._edges.add(edge)
        self._adjacency.setdefault(u, set()).add(v)
        self._adjacency.setdefault(v, set()).add(u)

    # ---- queries -----------------------------------------------------

    def connected(self, u: AgentID, v: AgentID) -> bool:
        """Return True if *u* and *v* share an edge."""
        return frozenset((u, v)) in self._edges

    def neighbours(self, agent_id: AgentID) -> List[AgentID]:
        """Return the neighbours of *agent_id*."""
        return sorted(self._adjacency.get(agent_id, set()))

    @property
    def nodes(self) -> List[AgentID]:
        """All nodes that appear in at least one edge."""
        return sorted(self._adjacency.keys())

    # ---- factories ---------------------------------------------------

    @classmethod
    def fully_connected(cls, agent_ids: List[AgentID]) -> "Topology":
        """Return a complete graph over the given agent IDs."""
        edges: List[Tuple[AgentID, AgentID]] = []
        for i, u in enumerate(agent_ids):
            for v in agent_ids[i + 1 :]:
                edges.append((u, v))
        return cls(edges)

    @classmethod
    def bipartite(
        cls, group_a: List[AgentID], group_b: List[AgentID]
    ) -> "Topology":
        """Return a complete bipartite graph (every a connected to every b)."""
        edges = [(a, b) for a in group_a for b in group_b]
        return cls(edges)

    def __repr__(self) -> str:
        edge_strs = [
            f"{sorted(e)}" for e in sorted(self._edges, key=lambda e: sorted(e))
        ]
        return f"Topology({', '.join(edge_strs)})"


# ======================================================================
# Role-specialised agent wrappers
# ======================================================================

class WorkerAgent(BaseAgent):
    """Wraps any BaseAgent and adds Worker semantics.

    The ``propose`` method calls the inner agent's ``choose_action`` and
    packages the result as a :class:`Proposal`.

    Parameters
    ----------
    inner : BaseAgent
        The agent whose ``choose_action`` provides the actual decision logic.
    default_confidence : float
        Confidence value used when the inner agent does not supply one.
    """

    role: Role = Role.WORKER

    def __init__(
        self,
        inner: BaseAgent,
        default_confidence: float = 0.5,
    ) -> None:
        super().__init__(
            agent_id=inner.agent_id,
            team_id=inner.team_id,
            config=inner.config,
        )
        self._inner = inner
        self._default_confidence = default_confidence

    # ---- core interface ----------------------------------------------

    def choose_action(
        self,
        observation: Observation,
        text_state: str,
        legal_moves: List[Action],
        game_rules: str,
    ) -> Action:
        """Delegate to the inner agent."""
        return self._inner.choose_action(
            observation, text_state, legal_moves, game_rules
        )

    def propose(
        self,
        observation: Observation,
        text_state: str,
        legal_moves: List[Action],
        game_rules: str,
    ) -> Proposal:
        """Generate a Proposal by invoking the inner agent.

        If the inner agent's ``choose_action`` result is a dict with keys
        ``action``, ``confidence``, ``rationale``, those are unpacked.
        Otherwise the raw return value is used as the action with defaults
        for confidence and rationale.
        """
        raw = self._inner.choose_action(
            observation, text_state, legal_moves, game_rules
        )

        # Allow rich responses from LLM-backed agents.
        if isinstance(raw, dict) and "action" in raw:
            action = raw["action"]
            confidence = float(raw.get("confidence", self._default_confidence))
            rationale = str(raw.get("rationale", ""))
        else:
            action = raw
            confidence = self._default_confidence
            rationale = ""

        return Proposal(
            agent_id=self.agent_id,
            action=action,
            confidence=confidence,
            rationale=rationale,
        )

    # ---- lifecycle delegation ----------------------------------------

    def on_episode_start(self, initial_obs: Observation, game_rules: str) -> None:
        self._inner.on_episode_start(initial_obs, game_rules)
        super().on_episode_start(initial_obs, game_rules)

    def on_episode_end(self, final_obs: Observation, total_reward: float) -> None:
        self._inner.on_episode_end(final_obs, total_reward)

    def on_step_end(
        self,
        observation: Observation,
        action: Action,
        reward: float,
        done: bool,
        info: Dict[str, Any],
    ) -> None:
        self._inner.on_step_end(observation, action, reward, done, info)

    @property
    def name(self) -> str:
        return f"WorkerAgent({self._inner.name})"


class ValidatorAgent(BaseAgent):
    """Wraps any BaseAgent and adds Validator semantics.

    The ``validate`` method evaluates a list of :class:`Proposal` objects
    and returns a :class:`Verdict` for each.

    The inner agent's ``choose_action`` is called once per proposal with
    the proposal details injected into the text state.  If the returned
    action (or its string representation) starts with ``"approve"``
    (case-insensitive) the proposal is approved; otherwise it is rejected.
    """

    role: Role = Role.VALIDATOR

    def __init__(self, inner: BaseAgent) -> None:
        super().__init__(
            agent_id=inner.agent_id,
            team_id=inner.team_id,
            config=inner.config,
        )
        self._inner = inner

    # ---- core interface ----------------------------------------------

    def choose_action(
        self,
        observation: Observation,
        text_state: str,
        legal_moves: List[Action],
        game_rules: str,
    ) -> Action:
        """Delegate to the inner agent."""
        return self._inner.choose_action(
            observation, text_state, legal_moves, game_rules
        )

    def validate(
        self,
        proposals: List[Proposal],
        observation: Observation,
        text_state: str,
        game_rules: str,
    ) -> List[Verdict]:
        """Evaluate each proposal and return verdicts.

        For each proposal the inner agent is asked to ``choose_action``
        with the legal moves ``["approve", "reject"]`` and the text state
        augmented with the proposal details.

        If the inner agent returns a dict with keys ``approved`` (bool)
        and ``reason`` (str), those are used directly.  Otherwise the
        raw action is interpreted as a string and matched
        case-insensitively against ``"approve"``.
        """
        verdicts: List[Verdict] = []
        validation_moves: List[Action] = ["approve", "reject"]

        for proposal in proposals:
            augmented_state = (
                f"{text_state}\n\n"
                f"--- PROPOSAL TO VALIDATE ---\n"
                f"Worker: {proposal.agent_id}\n"
                f"Action: {proposal.action}\n"
                f"Confidence: {proposal.confidence:.2f}\n"
                f"Rationale: {proposal.rationale}\n"
                f"----------------------------"
            )

            raw = self._inner.choose_action(
                observation, augmented_state, validation_moves, game_rules
            )

            # Parse rich response dicts from LLM-backed agents.
            if isinstance(raw, dict) and "approved" in raw:
                approved = bool(raw["approved"])
                reason = str(raw.get("reason", ""))
            else:
                action_str = str(raw).strip().lower()
                approved = action_str.startswith("approve")
                reason = str(raw)

            verdicts.append(
                Verdict(
                    proposal=proposal,
                    approved=approved,
                    reason=reason,
                    validator_id=self.agent_id,
                )
            )

        return verdicts

    # ---- lifecycle delegation ----------------------------------------

    def on_episode_start(self, initial_obs: Observation, game_rules: str) -> None:
        self._inner.on_episode_start(initial_obs, game_rules)
        super().on_episode_start(initial_obs, game_rules)

    def on_episode_end(self, final_obs: Observation, total_reward: float) -> None:
        self._inner.on_episode_end(final_obs, total_reward)

    def on_step_end(
        self,
        observation: Observation,
        action: Action,
        reward: float,
        done: bool,
        info: Dict[str, Any],
    ) -> None:
        self._inner.on_step_end(observation, action, reward, done, info)

    @property
    def name(self) -> str:
        return f"ValidatorAgent({self._inner.name})"


class ThinkerAgent(BaseAgent):
    """Wraps any BaseAgent and adds Thinker (readout) semantics.

    The ``integrate`` method receives the full list of verdicts from the
    validation phase and produces a single final :class:`Action`.

    Strategy
    --------
    1. Collect all *approved* proposals.
    2. If at least one proposal is approved the inner agent is asked to
       choose among the approved actions (presented as legal moves).
    3. If no proposal is approved the inner agent is given *all* proposed
       actions as fallback legal moves so the team can still act.
    """

    role: Role = Role.THINKER

    def __init__(self, inner: BaseAgent) -> None:
        super().__init__(
            agent_id=inner.agent_id,
            team_id=inner.team_id,
            config=inner.config,
        )
        self._inner = inner

    # ---- core interface ----------------------------------------------

    def choose_action(
        self,
        observation: Observation,
        text_state: str,
        legal_moves: List[Action],
        game_rules: str,
    ) -> Action:
        """Delegate to the inner agent."""
        return self._inner.choose_action(
            observation, text_state, legal_moves, game_rules
        )

    def integrate(
        self,
        verdicts: List[Verdict],
        observation: Observation,
        text_state: str,
        game_rules: str,
    ) -> Action:
        """Integrate validated proposals into a single team action.

        Returns
        -------
        Action
            The final action selected by the thinker.
        """
        approved = [v for v in verdicts if v.approved]

        if approved:
            candidate_actions = _unique_actions(
                [v.proposal.action for v in approved]
            )
            verdict_summary = _format_verdicts(verdicts, highlight_approved=True)
        else:
            # Fallback: let the thinker pick from all proposals.
            candidate_actions = _unique_actions(
                [v.proposal.action for v in verdicts]
            )
            verdict_summary = _format_verdicts(verdicts, highlight_approved=False)
            logger.warning(
                "No proposals were approved; thinker %s is choosing "
                "among all %d proposed actions as fallback.",
                self.agent_id,
                len(candidate_actions),
            )

        augmented_state = (
            f"{text_state}\n\n"
            f"--- DELIBERATION SUMMARY ---\n"
            f"{verdict_summary}\n"
            f"----------------------------\n"
            f"Select the best action from the candidates above."
        )

        action = self._inner.choose_action(
            observation, augmented_state, candidate_actions, game_rules
        )
        return action

    # ---- lifecycle delegation ----------------------------------------

    def on_episode_start(self, initial_obs: Observation, game_rules: str) -> None:
        self._inner.on_episode_start(initial_obs, game_rules)
        super().on_episode_start(initial_obs, game_rules)

    def on_episode_end(self, final_obs: Observation, total_reward: float) -> None:
        self._inner.on_episode_end(final_obs, total_reward)

    def on_step_end(
        self,
        observation: Observation,
        action: Action,
        reward: float,
        done: bool,
        info: Dict[str, Any],
    ) -> None:
        self._inner.on_step_end(observation, action, reward, done, info)

    @property
    def name(self) -> str:
        return f"ThinkerAgent({self._inner.name})"


# ======================================================================
# Team Orchestrator
# ======================================================================

class TeamOrchestrator:
    """Runs a single Worker-Validator-Thinker deliberation round.

    The orchestrator respects the topology graph: a Validator only
    evaluates proposals from Workers to which it is connected.

    Parameters
    ----------
    role_assignment : RoleAssignment
        Defines which agents hold which roles.
    agents : dict[AgentID, BaseAgent]
        Mapping of agent IDs to *role-wrapped* agent instances
        (WorkerAgent, ValidatorAgent, ThinkerAgent).  For small teams
        where the implicit thinker is a ValidatorAgent, the same object
        should appear under the validator key -- the orchestrator handles
        calling ``integrate`` on it by constructing an ad-hoc
        ThinkerAgent wrapper.
    topology : Topology, optional
        Communication graph.  Defaults to fully connected.

    Raises
    ------
    ValueError
        If agent IDs in the role assignment do not match the agents dict,
        or if role types do not match the assigned roles.
    """

    def __init__(
        self,
        role_assignment: RoleAssignment,
        agents: Dict[AgentID, BaseAgent],
        topology: Optional[Topology] = None,
    ) -> None:
        self._assignment = role_assignment
        self._agents = dict(agents)
        self._topology = topology or Topology.fully_connected(
            role_assignment.agent_ids
        )
        self._validate_agents()

    def _validate_agents(self) -> None:
        """Ensure every assigned agent ID has a matching entry in *agents*."""
        missing = set(self._assignment.agent_ids) - set(self._agents.keys())
        if missing:
            raise ValueError(
                f"Agents missing from the agents dict: {sorted(missing)}"
            )

    # ---- public API --------------------------------------------------

    def run_round(
        self,
        observation: Observation,
        text_state: str,
        legal_moves: List[Action],
        game_rules: str,
    ) -> RoundResult:
        """Execute one full deliberation round.

        Steps
        -----
        1. **Propose** -- every Worker generates a Proposal.
        2. **Validate** -- every Validator evaluates proposals from its
           connected Workers (per topology).
        3. **Integrate** -- the Thinker (explicit or implicit) selects
           the final action from the validated proposals.

        Returns
        -------
        RoundResult
            Complete audit trail and the chosen action.
        """
        llm_calls = 0

        # -- Step 1: Workers propose -----------------------------------
        proposals: List[Proposal] = []
        for wid in self._assignment.workers:
            agent = self._agents[wid]
            if isinstance(agent, WorkerAgent):
                proposal = agent.propose(
                    observation, text_state, legal_moves, game_rules
                )
            else:
                # Bare BaseAgent -- wrap on the fly.
                wrapper = WorkerAgent(agent)
                proposal = wrapper.propose(
                    observation, text_state, legal_moves, game_rules
                )
            proposals.append(proposal)
            llm_calls += 1

        logger.debug(
            "Workers produced %d proposal(s): %s",
            len(proposals),
            [p.action for p in proposals],
        )

        # -- Step 2: Validators validate (topology-aware) --------------
        all_verdicts: List[Verdict] = []
        for vid in self._assignment.validators:
            agent = self._agents[vid]

            # Filter proposals to those from connected workers.
            connected_proposals = [
                p
                for p in proposals
                if self._topology.connected(vid, p.agent_id)
            ]

            if not connected_proposals:
                logger.debug(
                    "Validator %s has no connected workers -- skipping.", vid
                )
                continue

            if isinstance(agent, ValidatorAgent):
                verdicts = agent.validate(
                    connected_proposals, observation, text_state, game_rules
                )
            else:
                wrapper = ValidatorAgent(agent)
                verdicts = wrapper.validate(
                    connected_proposals, observation, text_state, game_rules
                )
            all_verdicts.extend(verdicts)
            llm_calls += len(connected_proposals)

        logger.debug(
            "Validators produced %d verdict(s): approved=%d, rejected=%d",
            len(all_verdicts),
            sum(1 for v in all_verdicts if v.approved),
            sum(1 for v in all_verdicts if not v.approved),
        )

        # -- Step 3: Thinker integrates --------------------------------
        thinker_ids = self._assignment.effective_thinkers
        if not thinker_ids:
            raise RuntimeError(
                "No thinker available (explicit or implicit). "
                "Check the RoleAssignment."
            )

        thinker_id = thinker_ids[0]
        thinker_agent = self._agents[thinker_id]

        if isinstance(thinker_agent, ThinkerAgent):
            final_action = thinker_agent.integrate(
                all_verdicts, observation, text_state, game_rules
            )
        else:
            # Implicit thinker (ValidatorAgent doubling) or bare agent.
            wrapper = ThinkerAgent(thinker_agent if not isinstance(thinker_agent, ValidatorAgent) else thinker_agent._inner)
            final_action = wrapper.integrate(
                all_verdicts, observation, text_state, game_rules
            )
        llm_calls += 1

        logger.info(
            "Deliberation round complete: final_action=%s, "
            "proposals=%d, verdicts=%d, llm_calls=%d",
            final_action,
            len(proposals),
            len(all_verdicts),
            llm_calls,
        )

        return RoundResult(
            proposals=proposals,
            verdicts=all_verdicts,
            final_action=final_action,
            llm_calls=llm_calls,
        )


# ======================================================================
# Utility helpers (module-private)
# ======================================================================

def _unique_actions(actions: List[Action]) -> List[Action]:
    """De-duplicate actions while preserving order.

    Works with unhashable actions by falling back to an equality scan.
    """
    seen: list = []
    unique: List[Action] = []
    for a in actions:
        # Try fast hash-based membership first.
        try:
            hashable = hash(a)  # noqa: F841 -- only testing hashability
            key: Any = a
        except TypeError:
            key = str(a)

        if key not in seen:
            seen.append(key)
            unique.append(a)
    return unique


def _format_verdicts(verdicts: List[Verdict], highlight_approved: bool) -> str:
    """Render verdicts as a human-readable summary for the thinker prompt."""
    if not verdicts:
        return "(No verdicts received.)"

    lines: List[str] = []
    for v in verdicts:
        status = "APPROVED" if v.approved else "REJECTED"
        marker = " <<" if (highlight_approved and v.approved) else ""
        lines.append(
            f"  [{status}] Action={v.proposal.action} "
            f"(worker={v.proposal.agent_id}, confidence={v.proposal.confidence:.2f}) "
            f"-- Validator {v.validator_id}: {v.reason}{marker}"
        )
    return "\n".join(lines)
